name: GitHub-Actions

run-name: ${{ github.actor }} is testing out GitHub Actions

on: 
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
    
jobs:

  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Event Name ${{ github.event_name }}"
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."

  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials from sandbox account
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::072737625154:role/oblcc/oblcc-admin
        aws-region: us-east-1
    - name: Copy files to the test website with the AWS CLI
      run: |
        aws s3api create-bucket --bucket mohan -github-actions-bucket-2023 --region us-east-1
